### ISSUE TITLE
GARMIN Varia ertl615

### ISSUE THREAD

**Issue by Roland2309** [maca88/SmartBikeLights#61]
Hello
Can you also integrate the eRTL615 radar?
I tried to select the Varia 515 with the editor but it doesn't work... neither the functions e.g. sunset/sunrise nor the data field with 1 field are displayed... can you help me

Thank you
Roland

**Comment by maca88** [comment]
Hi,

In order to add support for eRTL615, I need the supported light modes for the light. If you own eRTL615, please clean the "Lights configuration" app setting (leave empty) and report back what numbers do see on the screen and what mode each number represents.
For example:
1 -> High
5 -> Low
7 -> Day Flash
8 -> Nigh Flash

**Comment by Roland2309** [comment]
Hi
Thanks for the answer...but where can I see the numbers...when I make a data page with one field I get an empty field...when I make a data page with 2 fields I get the icon and the battery and a question mark...i have a garmin 1040

**Comment by maca88** [comment]
You need to put the data field to a 1 field layout data screen and clear the "Lights Configuration" app setting. 

> when I make a data page with one field I get an empty field

Do you see just an empty screen or there is a text in the middle of the screen (e.g. "Error X")?

**Comment by Roland2309** [comment]
That's exactly what I did...the configurations field is empty and I have a data page with one field....no errors...the field is absolutely empty

**Comment by Roland2309** [comment]
can you help me further?

**Comment by maca88** [comment]
That is very strange, I am not able to reproduce the empty screen with my lights. If you are willing to help further research what is wrong, you can use a special debugging tool used for cases like this.

Here are the steps:

1. Download the `LightTester` widget for Edge 1040: https://github.com/maca88/SmartBikeLights/blob/tester/Source/LightTester/build/edge1040/LightTester.prg
2. Follow the `LightTester` steps described here: https://github.com/maca88/SmartBikeLights/tree/tester/Source/LightTester#how-to-use
3. Post the content of the `LightTester.TXT` file

When you open the widget, make sure to go through all light modes by using the physical button on the light, so that they will be logged in the file.

I am interested to see what you will see for:
- CM (Capable modes)
- TY (Light type)
- LM (Light mode)
- BS (Battery state)

**Comment by Roland2309** [comment]
Hi 
This is the content of the Lighttester.txt file...I have pushed through all modes:

Net ST=2 MD=0 T=74123
T_L: 1
L0: TY=2 ID=1 LM=0 CM=[0, 4, 5, 6, 7] BS=7
UPD: TY=2 ID=1 LM=7 BS=7 T=81475
UPD: TY=2 ID=1 LM=4 BS=7 T=86479
UPD: TY=2 ID=1 LM=5 BS=7 T=89479
UPD: TY=2 ID=1 LM=6 BS=7 T=93481
UPD: TY=2 ID=1 LM=7 BS=7 T=98483
UPD: TY=2 ID=1 LM=4 BS=7 T=103483
UPD: TY=2 ID=1 LM=0 BS=7 T=106485

**Comment by maca88** [comment]
Thanks for the taking the time and providing the results! Now it make sense why you see an empty screen. The issue is with "BS=7", battery state 7 is defined as "INVALID" according the ANT specification, that is why Smart Bike Lights is showing an empty screen.
I will release an update to support also battery state 7. In the meantime, can you provide me the light modes names? Based on the above result, the light has the following light modes (LM):
0 -> OFF
4 -> ???
5 -> ???
6 -> ???
7 -> ???

In order to add the light to the configuration, I would need the light mode names for each number (e.g. 6 -> Day Flash). With the LightTester widget open, you can see the current light mode in the "LM" label, which you can use to map the names to numbers

**Comment by Roland2309** [comment]
4=Solid-Modus
5=Peloton-Modus
6=Night Flash Modus
7=Day Flash Modus

Thank you very much for your support
br
roland

**Comment by maca88** [comment]
Thanks for the light modes! I've released version `0.26.6` which should work with eRTL615 and added it to the Lights Configurator

**Comment by Roland2309** [comment]
Thank you very much for your help ! everything works perfectly!

The Bike Lights app doesn't work yet...you probably haven't changed that yet!

Best regards
Roland

**Comment by maca88** [comment]
Now also the Bike Lights Control widget was updated (version 0.15.5) to work with eRTL615.

Thanks again for the help!
