### ISSUE TITLE
Error 3 Smart bike light 

### ISSUE THREAD

**Issue by Kacper1891** [maca88/SmartBikeLights#70]
Hi, 
I've tried to configure two headlights with Smart Bike light #2, but it shows Error 3.
Do I have to instal Smart bike light and Smart bike light #2.

I have varia ut800 and trek ion200

Many thanks for your help

Regards

**Comment by maca88** [comment]
Hi,

Yes, for configuring two different headlights you need to install also `Smart Bike Lights #2`. 
The most likely reason for Error 3 is that the serial number was not set in the configuration. In your case, you need to set the serial number of each light, which means that you need two configurations:
1. UT800 configuration for `Smart Bike Lights`
2.  ION200 configuration for `Smart Bike Lights #2`

both configurations need to have the serial number set. You can get the serial number of each lights under Garmin Sensors -> Light menu. Make sure that you set the correct serial, otherwise you will see "No Network".

**Comment by Kacper1891** [comment]
Hi There, 

Many thanks for your help.
It's working now as it should.
Regards
